# Generated by Django 5.2.7 on 2025-10-20 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_autor_livros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='autor',
        ),
        migrations.AddField(
            model_name='livros',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='livraria.autor'),
        ),
        migrations.AddField(
            model_name='livros',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='livros',
            name='ISBN',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.categoria'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.editora'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
